# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getRegionCPP <- function(x, y) {
    .Call('_HGrM_getRegionCPP', PACKAGE = 'HGrM', x, y)
}

checkRegionCPP <- function(x, y) {
    .Call('_HGrM_checkRegionCPP', PACKAGE = 'HGrM', x, y)
}

